import pandas as pd
import geopandas as gpd


def read_data_country():
    # https://github.com/owid/covid-19-data/blob/master/public/data/owid-covid-data.csv
    df_world = pd.read_csv("../data/owid-covid-data.csv")
    df_sweden = df_world[df_world['location'] == 'Sweden']
    df_sweden['date'] = pd.to_datetime(df_sweden['date'])
    df_sweden.set_index('date', inplace=True)

    return df_world, df_sweden


def millions(x, pos):
    return '%1.1fM' % (x * 1e-6)


def read_regional_data(file: str):
    shp = '../data/gadm41_SWE_1.shp'
    map_df = gpd.read_file(shp)
    map_df = map_df.set_crs(4326, allow_override=True)
    data_proj = map_df.to_crs(epsg=3035)
    data_proj.insert(1, "Region", ['Blekinge', 'Dalarna', 'Gävleborg', 'Gotland', 'Halland', 'Jämtland', 'Jönköping', 'Kalmar', 'Kronoberg', 'Norrbotten', 'Orebro', 'Östergötland', 'Skåne', 'Södermanland', 'Stockholm', 'Uppsala', 'Värmland', 'Västerbotten', 'Västernorrland', 'Västmanland', 'Västra Götaland'], True)
    return data_proj, pd.read_csv(f'../data/{file}.csv', encoding='ISO-8859-1')


WEEKS_TO_MONTHS = {
    '2020': {
        'w1': 'January',
        'w2': 'January',
        'w3': 'January',
        'w4': 'January',
        'w5': 'January',
        'w6': 'February',
        'w7': 'February',
        'w8': 'February',
        'w9': 'February',
        'w10': 'March',
        'w11': 'March',
        'w12': 'March',
        'w13': 'March',
        'w14': 'April',
        'w15': 'April',
        'w16': 'April',
        'w17': 'April',
        'w18': 'April',
        'w19': 'May',
        'w20': 'May',
        'w21': 'May',
        'w22': 'May',
        'w23': 'June',
        'w24': 'June',
        'w25': 'June',
        'w26': 'June',
        'w27': 'July',
        'w28': 'July',
        'w29': 'July',
        'w30': 'July',
        'w31': 'July',
        'w32': 'August',
        'w33': 'August',
        'w34': 'August',
        'w35': 'August',
        'w36': 'September',
        'w37': 'September',
        'w38': 'September',
        'w39': 'September',
        'w40': 'October',
        'w41': 'October',
        'w42': 'October',
        'w43': 'October',
        'w44': 'October',
        'w45': 'November',
        'w46': 'November',
        'w47': 'November',
        'w48': 'November',
        'w49': 'December',
        'w50': 'December',
        'w51': 'December',
        'w52': 'December',
        'w53': 'December',
    },
    '2021': {
        'w1': 'January',
        'w2': 'January',
        'w3': 'January',
        'w4': 'January',
        'w5': 'January',
        'w6': 'February',
        'w7': 'February',
        'w8': 'February',
        'w9': 'February',
        'w10': 'March',
        'w11': 'March',
        'w12': 'March',
        'w13': 'March',
        'w14': 'April',
        'w15': 'April',
        'w16': 'April',
        'w17': 'April',
        'w18': 'April',
        'w19': 'May',
        'w20': 'May',
        'w21': 'May',
        'w22': 'May',
        'w23': 'June',
        'w24': 'June',
        'w25': 'June',
        'w26': 'June',
        'w27': 'July',
        'w28': 'July',
        'w29': 'July',
        'w30': 'July',
        'w31': 'July',
        'w32': 'August',
        'w33': 'August',
        'w34': 'August',
        'w35': 'August',
        'w36': 'September',
        'w37': 'September',
        'w38': 'September',
        'w39': 'September',
        'w40': 'September',
        'w41': 'October',
        'w42': 'October',
        'w43': 'October',
        'w44': 'October',
        'w45': 'November',
        'w46': 'November',
        'w47': 'November',
        'w48': 'November',
        'w49': 'December',
        'w50': 'December',
        'w51': 'December',
        'w52': 'December',
        'w53': 'December',
    },
    '2022': {
        'w1': 'January',
        'w2': 'January',
        'w3': 'January',
        'w4': 'January',
        'w5': 'January',
        'w6': 'February',
        'w7': 'February',
        'w8': 'February',
        'w9': 'February',
        'w10': 'March',
        'w11': 'March',
        'w12': 'March',
        'w13': 'March',
        'w14': 'March',
        'w15': 'April',
        'w16': 'April',
        'w17': 'April',
        'w18': 'April',
        'w19': 'May',
        'w20': 'May',
        'w21': 'May',
        'w22': 'May',
        'w23': 'June',
        'w24': 'June',
        'w25': 'June',
        'w26': 'June',
        'w27': 'June',
        'w28': 'July',
        'w29': 'July',
        'w30': 'July',
        'w31': 'July',
        'w32': 'August',
        'w33': 'August',
        'w34': 'August',
        'w35': 'August',
        'w36': 'September',
        'w37': 'September',
        'w38': 'September',
        'w39': 'September',
        'w40': 'September',
        'w41': 'October',
        'w42': 'October',
        'w43': 'October',
        'w44': 'October',
        'w45': 'November',
        'w46': 'November',
        'w47': 'November',
        'w48': 'November',
        'w49': 'December',
        'w50': 'December',
        'w51': 'December',
        'w52': 'December',
        'w53': 'December',
    },
    '2023': {
        'w1': 'January',
        'w2': 'January',
        'w3': 'January',
        'w4': 'January',
        'w5': 'January',
        'w6': 'February',
        'w7': 'February',
        'w8': 'February',
        'w9': 'February',
        'w10': 'March',
        'w11': 'March',
        'w12': 'March',
        'w13': 'March',
        'w14': 'March',
        'w15': 'April',
        'w16': 'April',
        'w17': 'April',
        'w18': 'April',
        'w19': 'May',
        'w20': 'May',
        'w21': 'May',
        'w22': 'May',
        'w23': 'June',
        'w24': 'June',
        'w25': 'June',
        'w26': 'June',
        'w27': 'June',
        'w28': 'July',
        'w29': 'July',
        'w30': 'July',
        'w31': 'July',
        'w32': 'August',
        'w33': 'August',
        'w34': 'August',
        'w35': 'August',
        'w36': 'August',
        'w37': 'September',
        'w38': 'September',
        'w39': 'September',
        'w40': 'September',
        'w41': 'October',
        'w42': 'October',
        'w43': 'October',
        'w44': 'October',
        'w45': 'November',
        'w46': 'November',
        'w47': 'November',
        'w48': 'November',
        'w49': 'November',
        'w50': 'December',
        'w51': 'December',
        'w52': 'December',
        'w53': 'December',
    }
}
